### ISSUE TITLE
Starter 连接 Embed Mongo 失败

### ISSUE THREAD

**Issue by rj-hwang** [simter/simter-file#19]
1. 使用 `mvn spring-boot:run -P dev-postgres` 启动 [simter-file-starter (6d580b7)](https://github.com/simter/simter-file/commit/6d580b725f1731dd8d5c87d8ecaa2dc93212fd15)。
2. 使用 `npm start` 启动  [simter-file-static (258fbd4)](https://github.com/simter/simter-file-static/commit/258fbd42454dae04a57a15ef30c434d250a88f21)。
3. 打开 <http://localhost:1234/> 的 Upload 连接。
4. 选择一个文件然后点击 Submit 执行上传文件操作，后台报如下错误而无法上传成功：

```
2018-01-31 11:26:34.819 ERROR 28052 --- [3fdcc6d94801379] .a.w.r.e.DefaultErrorWebExceptionHandler : Failed to handle request [POST http://localhost:9013/]

org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='file', source='file', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='file', source='file', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]
  at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:87) ~[spring-data-mongodb-2.0.2.RELEASE.jar:2.0.2.RELEASE]
  at org.springframework.data.mongodb.core.ReactiveMongoTemplate.potentiallyConvertRuntimeException(ReactiveMongoTemplate.java:2197) ~[spring-data-mongodb-2.0.2.RELEASE.jar:2.0.2.RELEASE]
  at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$translateException$54(ReactiveMongoTemplate.java:2180) ~[spring-data-mongodb-2.0.2.RELEASE.jar:2.0.2.RELEASE]
  at reactor.core.publisher.Mono.lambda$onErrorMap$20(Mono.java:2427) ~[reactor-core-3.1.2.RELEASE.jar:3.1.2.RELEASE]
  at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ~[reactor-core-3.1.2.RELEASE.jar:3.1.2.RELEASE]
  at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:132) ~[reactor-core-3.1.2.RELEASE.jar:3.1.2.RELEASE]
  at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120) ~[reactor-core-3.1.2.RELEASE.jar:3.1.2.RELEASE]
  at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87) ~[reactor-core-3.1.2.RELEASE.jar:3.1.2.RELEASE]
  at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onError(ObservableToPublisher.java:73) ~[mongodb-driver-reactivestreams-1.6.0.jar:na]
  at com.mongodb.async.client.AbstractSubscription.onError(AbstractSubscription.java:123) ~[mongodb-driver-async-3.5.0.jar:na]
  at com.mongodb.async.client.SingleResultCallbackSubscription$1.onResult(SingleResultCallbackSubscription.java:42) ~[mongodb-driver-async-3.5.0.jar:na]
  at com.mongodb.async.client.MongoCollectionImpl$3.onResult(MongoCollectionImpl.java:399) ~[mongodb-driver-async-3.5.0.jar:na]
  at com.mongodb.async.client.MongoCollectionImpl$3.onResult(MongoCollectionImpl.java:395) ~[mongodb-driver-async-3.5.0.jar:na]
  at com.mongodb.async.client.MongoCollectionImpl$8.onResult(MongoCollectionImpl.java:641) ~[mongodb-driver-async-3.5.0.jar:na]
  at com.mongodb.async.client.MongoCollectionImpl$8.onResult(MongoCollectionImpl.java:625) ~[mongodb-driver-async-3.5.0.jar:na]
  at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.async.client.MongoClientImpl$2$2.onResult(MongoClientImpl.java:144) ~[mongodb-driver-async-3.5.0.jar:na]
  at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.operation.MixedBulkWriteOperation$2.call(MixedBulkWriteOperation.java:202) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionCallback.onResult(OperationHelper.java:459) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionCallback.onResult(OperationHelper.java:451) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:79) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:75) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:407) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:292) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.connection.BaseCluster.access$800(BaseCluster.java:55) ~[mongodb-driver-core-3.5.0.jar:na]
  at com.mongodb.connection.BaseCluster$WaitQueueHandler.run(BaseCluster.java:456) ~[mongodb-driver-core-3.5.0.jar:na]
  at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='file', source='file', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]
  at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375) ~[mongodb-driver-core-3.5.0.jar:na]
  ... 4 common frames omitted
```

**Comment by BallsperCat** [comment]
Create branch: hotfix/mongo-access-timeout, starting handle this issue.

**Comment by BallsperCat** [comment]
【任务汇报】在本地调试开发配置的上传功能时发现删除 "spring.data.mongodb.port" 配置后上传功能就正常执行，推断是和 embed 配置冲突导致此错误。已将 mongodb 拆分为正式数据库和内存数据库两份配置，本地测试正常通过，提交详见：[5a2cd2](https://github.com/simter/simter-file/commit/5a2cd2b3a01613d27e5c57aa37b976974733b9f5)。

**Comment by BallsperCat** [comment]
已将修改内容已合并到 master 分支，详见：[3440b2](https://github.com/simter/simter-file/commit/3440b2931b079087c4564ed96fbc8d409a35f448)。
